######################################## What you will learn #######################################

# > Understand kmeans clustering.
# > Understand retail Data for applying kmeans clustering.
# > Understand the objective
# > Maths of kmeans clustering
# > understand Optimum number of cluster.
# > Using elbow method to determine the optimal number of cluster.
# > model fitting
# > Evaluation

# > Objective

# The client is a leading Fashion retailer in Australia. Company runs a display advertising campaign 
# for this brand, where it shows ads to users leading them to make a purchase on the brands website. 
# The given dataset is the Sales data for all users who made a purchase online in the first half 
# of October '17.

# Based on your analysis, arrive at a statistical segmentation of the brands audience based 
# on Revenue. The number of segments is up to you. Please provide definitions of each groups.

# > Maths of kmeans
#
# D = {1,2,3,7,8,9}
# we need to make two clusters using kmeans 
# centroid 1 = 2, centroid 2 = 8 #if not given we select randomly two number from the given data
# 
# Cluster 1 = {1,2,3}, Cluster 2 = {6,8,9}
# centroid 1 = 2, centroid 2 = 8

# > desired Library installation

#install.packages("factoextra")
#install.packages("rpivotTable")
#install.packages("cluster")
#install.packages("fpc")
#install.packages("factoextra")
#install.packages("rpivotTable")
#install.packages("ggplot2")
#install.packages("dplyr")
#install.packages("magrittr")

library(ggplot2) #visualisation
library(dplyr) #Data Manipulation
library(magrittr) #A forward pipe operator in R
library(cluster) #for Clustering
library(fpc) #Flexible procedures for Clustering

# > Setting working directory

getwd()
path <-
  "D:/S/StepUp_Online Course/Project Based Learning - Data Science and Analytics using R and MySQL/Course Content/KMeans Clustering/ClusterAnalysis"
setwd(path)

# > reading data

fashion <- read.csv("Fashion.csv", header = T)
View(fashion)

# > subsetting data to fit kmeans clustering

D <- subset(fashion, select = 20)
names(D)
class(D)
class(D$Revenue.AUD.)
glimpse(D)

# > fitting basic model taking a random number of cluster say "2"

basicmodel <- kmeans(D, 2)

basiccluster <- basicmodel$cluster #Cluster Allocation
basicmodel$totss #total sum of square
basicmodel$withinss #vector of within-cluster sum of square, one component per cluster
basicmodel$tot.withinss #sum of withinss
basicmodel$betweenss #totss - totwithinss

ggplot(data = D) +aes(x = basiccluster, y = Revenue.AUD.) + 
  geom_point() + xlab("Cluster") + ylab("Revenue")

# > calculating optimum number cluster

optimcluster <- function(k){
  cluster <- kmeans(D, k)
  return(cluster$tot.withinss)
}

wss <- sapply(1:20, optimcluster)
optimK <- data.frame(k = 1:20, wss)
head(optimK)

### ploting the k value from 1 to 20 against within sum of square (wss)

ggplot(data = optimK) + aes(x=k, y= wss) + geom_point() + geom_line()+
  scale_x_continuous(breaks = seq(1,20,by = 1))

OptimunCluster <- 3 #After the value 4, its very clear that wss is decreasing very slowly

# > Model fitting using kmeans function

model <- kmeans(D, OptimunCluster)

# > clusters from model

cluster <- model$cluster

# > centers of cluster (mean)

model$centers

# Data frame for original variable "Revenue" and "Cluster"

mapping <- data.frame(Revenue = D, Cluster = cluster)

# > visualisation using optimum cluster

ggplot(data = mapping) + aes(x = Cluster, y = D$Revenue.AUD.) +
  geom_point() + xlab("Cluster") + ylab("Revenue")

write.csv(mapping,"mapping.csv")

# > visualisation

plotcluster(D$Revenue.AUD., cluster)

################################################### END ###############################################